### ISSUE TITLE
Polacode not working on MacOs 14 + VS Code 1.82.2

### ISSUE THREAD

**Issue by ottopic** [octref/polacode#183]
Extension start, but nothing change when I select text.
Inside extension's marketplace on runtime status I have many errors of "panel.postMessage is not a function"
